-- =============================================================================
-- IAM Service — V1 통합 (Oracle Edition)
-- 구성: 스키마 DDL + 인덱스 + 시드 데이터 (V1~V3 통합)
-- Target DB: his_iam (Oracle XE 21c / XEPDB1)
-- 통합 방식:
--   V3의 PL/SQL BEGIN...END;/ 블록 제거
--   → 인덱스를 스키마 테이블 생성 직후에 CREATE INDEX로 직접 선언
--   → Flyway Community Oracle 파서 안정성 확보
-- =============================================================================

-- ============================================================
-- SECTION 1: DDL — 테이블 + 인덱스 생성
-- ============================================================

CREATE TABLE role (
    role_code  VARCHAR2(20)  NOT NULL,
    role_name  VARCHAR2(255) NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (role_code)
);

CREATE TABLE permission (
    perm_code   VARCHAR2(40)  NOT NULL,
    perm_name   VARCHAR2(255) NOT NULL,
    description VARCHAR2(255) NULL,
    CONSTRAINT pk_permission PRIMARY KEY (perm_code)
);

CREATE TABLE role_permission (
    id        NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    role_code VARCHAR2(20)  NOT NULL,
    perm_code VARCHAR2(40)  NOT NULL,
    CONSTRAINT pk_role_permission PRIMARY KEY (id),
    CONSTRAINT uk_role_perm UNIQUE (role_code, perm_code)
);
CREATE INDEX idx_role_perm_role ON role_permission (role_code);
CREATE INDEX idx_role_perm_perm ON role_permission (perm_code);

CREATE TABLE user_account (
    user_id       NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    login_id      VARCHAR2(255) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    staff_id      VARCHAR2(255) NOT NULL,
    active        NUMBER(1)     NOT NULL,
    CONSTRAINT pk_user_account PRIMARY KEY (user_id),
    CONSTRAINT uk_user_account_login_id UNIQUE (login_id)
);
CREATE INDEX idx_user_account_active ON user_account (active);

CREATE TABLE user_role (
    id        NUMBER       GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    user_id   NUMBER       NOT NULL,
    role_code VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_user_role PRIMARY KEY (id),
    CONSTRAINT uk_user_role_user_role UNIQUE (user_id, role_code)
);
CREATE INDEX idx_user_role_user ON user_role (user_id);
CREATE INDEX idx_user_role_role ON user_role (role_code);

CREATE TABLE audit_log (
    event_id       VARCHAR2(40)   NOT NULL,
    actor_login_id VARCHAR2(255)  NOT NULL,
    service_name   VARCHAR2(255)  NOT NULL,
    action         VARCHAR2(255)  NOT NULL,
    result         VARCHAR2(255)  NOT NULL,
    target_type    VARCHAR2(255)  NULL,
    target_id      VARCHAR2(255)  NULL,
    patient_id     NUMBER         NULL,
    ip_address     VARCHAR2(255)  NULL,
    user_agent     VARCHAR2(1000) NULL,
    created_at     TIMESTAMP      NOT NULL,
    archived       NUMBER(1)      DEFAULT 0 NOT NULL,
    archived_at    TIMESTAMP      NULL,
    detail_json    CLOB           NULL,
    CONSTRAINT pk_audit_log PRIMARY KEY (event_id)
);
CREATE INDEX idx_audit_created_at ON audit_log (created_at);
CREATE INDEX idx_audit_actor      ON audit_log (actor_login_id);
CREATE INDEX idx_audit_action     ON audit_log (action);
CREATE INDEX idx_audit_service    ON audit_log (service_name);
CREATE INDEX idx_audit_result     ON audit_log (result);

-- ============================================================
-- SECTION 2: SEED — 기준 데이터
-- ============================================================

-- ── roles ────────────────────────────────────────────────────
MERGE INTO role t
USING (
    SELECT 'SYS'   AS role_code, 'System'        AS role_name FROM dual UNION ALL
    SELECT 'ADMIN',              'Administrator'              FROM dual UNION ALL
    SELECT 'DOC',                'Doctor'                     FROM dual UNION ALL
    SELECT 'NUR',                'Nurse'                      FROM dual UNION ALL
    SELECT 'LAB',                'Laboratory'                 FROM dual UNION ALL
    SELECT 'RAD',                'Radiology'                  FROM dual UNION ALL
    SELECT 'PHARM',              'Pharmacy'                   FROM dual UNION ALL
    SELECT 'PROC',               'Procedure'                  FROM dual
) s ON (t.role_code = s.role_code)
WHEN MATCHED THEN
    UPDATE SET t.role_name = s.role_name
WHEN NOT MATCHED THEN
    INSERT (role_code, role_name) VALUES (s.role_code, s.role_name);

-- ── permissions ──────────────────────────────────────────────
MERGE INTO permission t
USING (
    SELECT 'AUTH_LOGIN'   AS perm_code, 'Login'       AS perm_name, 'Authentication login' AS description FROM dual UNION ALL
    SELECT 'AUTH_REFRESH',              'Refresh',                   'Refresh token'                      FROM dual UNION ALL
    SELECT 'AUDIT_WRITE',               'Audit',                     'Write audit logs'                   FROM dual
) s ON (t.perm_code = s.perm_code)
WHEN MATCHED THEN
    UPDATE SET t.perm_name = s.perm_name, t.description = s.description
WHEN NOT MATCHED THEN
    INSERT (perm_code, perm_name, description) VALUES (s.perm_code, s.perm_name, s.description);

-- ── role_permission ──────────────────────────────────────────
MERGE INTO role_permission t
USING (
    SELECT 'SYS'   AS role_code, 'AUTH_LOGIN'   AS perm_code FROM dual UNION ALL
    SELECT 'SYS',                'AUTH_REFRESH'               FROM dual UNION ALL
    SELECT 'SYS',                'AUDIT_WRITE'                FROM dual UNION ALL
    SELECT 'ADMIN',              'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'ADMIN',              'AUTH_REFRESH'               FROM dual UNION ALL
    SELECT 'ADMIN',              'AUDIT_WRITE'                FROM dual UNION ALL
    SELECT 'DOC',                'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'NUR',                'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'LAB',                'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'RAD',                'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'PHARM',              'AUTH_LOGIN'                 FROM dual UNION ALL
    SELECT 'PROC',               'AUTH_LOGIN'                 FROM dual
) s ON (t.role_code = s.role_code AND t.perm_code = s.perm_code)
WHEN NOT MATCHED THEN
    INSERT (role_code, perm_code) VALUES (s.role_code, s.perm_code);

-- ── user_account ─────────────────────────────────────────────
MERGE INTO user_account t
USING (
    SELECT 'system' AS login_id, '$2b$10$BoHJSr/voZw6hw2HwR4ILOES9cmA5usWEjJXWfnYrROuJSG49W0s6' AS password_hash, 'SYS-001'   AS staff_id, 1 AS active FROM dual UNION ALL
    SELECT 'admin',              '$2b$10$DqllEy7YOBly2Qhxj0PI1.bnH59292qbhVNzdc1pZuCenNlybCaoO',               'ADMIN-001',              1             FROM dual UNION ALL
    SELECT 'doctor',             '$2b$10$OLG/JnywJGkCX/M6tjAOiOwOuXnLAjLuyzKQSduHrcdBCuVIS0teW',               'DOC-001',                1             FROM dual UNION ALL
    SELECT 'nurse',              '$2b$10$pArrWLeHnHk36nGvthFcYeVey.PvpefbLJBjEwva7XhpJKZrgyvwi',               'NUR-001',                1             FROM dual UNION ALL
    SELECT 'lab',                '$2b$10$WNvCdOO.gsXm3odIkVS9qeTCCOi0REMtcbN0h9J9ZTwZDpqIMJAwS',               'LAB-001',                1             FROM dual UNION ALL
    SELECT 'rad',                '$2b$10$GGBsfQikzwBOsFOzs7kDGuHLi65dfvsSRQjNiTI7OwemVshD4FUUm',               'RAD-001',                1             FROM dual UNION ALL
    SELECT 'pharm',              '$2b$10$JhoHWw3AWYvAhMR3f94GDeDRP35I5pRjypiDiGYqytrmr4rxzbu.m',               'PHARM-001',              1             FROM dual UNION ALL
    SELECT 'proc',               '$2b$10$hP9cP5z1wviT0qVtWf.3FuxNGJv3GxW4TTS1fQ/4EHGgVmy6OeK8m',               'PROC-001',               1             FROM dual
) s ON (t.login_id = s.login_id)
WHEN MATCHED THEN
    UPDATE SET t.password_hash = s.password_hash, t.staff_id = s.staff_id, t.active = s.active
WHEN NOT MATCHED THEN
    INSERT (login_id, password_hash, staff_id, active)
    VALUES (s.login_id, s.password_hash, s.staff_id, s.active);

-- ── user_role ────────────────────────────────────────────────
MERGE INTO user_role t
USING (
    SELECT ua.user_id, x.role_code
    FROM (
        SELECT 'system' AS login_id, 'SYS'   AS role_code FROM dual UNION ALL
        SELECT 'admin',              'ADMIN'               FROM dual UNION ALL
        SELECT 'doctor',             'DOC'                 FROM dual UNION ALL
        SELECT 'nurse',              'NUR'                 FROM dual UNION ALL
        SELECT 'lab',                'LAB'                 FROM dual UNION ALL
        SELECT 'rad',                'RAD'                 FROM dual UNION ALL
        SELECT 'pharm',              'PHARM'               FROM dual UNION ALL
        SELECT 'proc',               'PROC'                FROM dual
    ) x
    JOIN user_account ua ON ua.login_id = x.login_id
) s ON (t.user_id = s.user_id AND t.role_code = s.role_code)
WHEN NOT MATCHED THEN
    INSERT (user_id, role_code) VALUES (s.user_id, s.role_code);

COMMIT;
