-- =============================================================================
-- IAM baseline V1 schema — Oracle Edition
-- Target DB: his_iam (Oracle XE 21c 스키마)
-- [MODIFIED] AUTO_INCREMENT → GENERATED BY DEFAULT ON NULL AS IDENTITY
-- [MODIFIED] TINYINT(1) → NUMBER(1)
-- [MODIFIED] DATETIME → TIMESTAMP
-- [MODIFIED] TEXT → CLOB
-- [REMOVED] ENGINE=InnoDB, CHARSET, COLLATE
-- [REMOVED] CREATE TABLE IF NOT EXISTS → CREATE TABLE
--            이유: Oracle 21c는 IF NOT EXISTS 미지원 (23c+부터 지원)
--                 Flyway Oracle 파서가 해당 구문 파싱 불가 → Incomplete statement 오류
-- [REMOVED] 컬럼 인라인 주석(--) → Flyway Oracle 파서 안정성 확보
-- =============================================================================

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE role (
                      role_code  VARCHAR2(20)  NOT NULL,
                      role_name  VARCHAR2(255) NOT NULL,
                      CONSTRAINT pk_role PRIMARY KEY (role_code)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE permission (
                            perm_code   VARCHAR2(40)  NOT NULL,
                            perm_name   VARCHAR2(255) NOT NULL,
                            description VARCHAR2(255) NULL,
                            CONSTRAINT pk_permission PRIMARY KEY (perm_code)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE role_permission (
                                 id        NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                 role_code VARCHAR2(20)  NOT NULL,
                                 perm_code VARCHAR2(40)  NOT NULL,
                                 CONSTRAINT pk_role_permission PRIMARY KEY (id),
                                 CONSTRAINT uk_role_perm UNIQUE (role_code, perm_code)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE user_account (
                              user_id       NUMBER        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                              login_id      VARCHAR2(255) NOT NULL,
                              password_hash VARCHAR2(255) NOT NULL,
                              staff_id      VARCHAR2(255) NOT NULL,
                              active        NUMBER(1)     NOT NULL,
                              CONSTRAINT pk_user_account PRIMARY KEY (user_id),
                              CONSTRAINT uk_user_account_login_id UNIQUE (login_id)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE user_role (
                           id        NUMBER       GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                           user_id   NUMBER       NOT NULL,
                           role_code VARCHAR2(20) NOT NULL,
                           CONSTRAINT pk_user_role PRIMARY KEY (id),
                           CONSTRAINT uk_user_role_user_role UNIQUE (user_id, role_code)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE audit_log (
                           event_id       VARCHAR2(40)   NOT NULL,
                           actor_login_id VARCHAR2(255)  NOT NULL,
                           service_name   VARCHAR2(255)  NOT NULL,
                           action         VARCHAR2(255)  NOT NULL,
                           result         VARCHAR2(255)  NOT NULL,
                           target_type    VARCHAR2(255)  NULL,
                           target_id      VARCHAR2(255)  NULL,
                           patient_id     NUMBER         NULL,
                           ip_address     VARCHAR2(255)  NULL,
                           user_agent     VARCHAR2(1000) NULL,
                           created_at     TIMESTAMP      NOT NULL,
                           archived       NUMBER(1)      DEFAULT 0 NOT NULL,
                           archived_at    TIMESTAMP      NULL,
                           detail_json    CLOB           NULL,
                           CONSTRAINT pk_audit_log PRIMARY KEY (event_id)
);