-- =============================================================================
-- Support Service Initial Schema (V1) — Oracle Edition
-- Target DB: his_support (Oracle XE 21c 스키마)
-- [MODIFIED] AUTO_INCREMENT → GENERATED BY DEFAULT ON NULL AS IDENTITY
-- [MODIFIED] LONGTEXT / TEXT → CLOB
-- [MODIFIED] TINYINT(1) → NUMBER(1)
-- [MODIFIED] DATETIME → TIMESTAMP
-- [MODIFIED] INDEX (인라인) → CREATE INDEX 별도 선언
-- [REMOVED] ENGINE=InnoDB, DEFAULT CHARSET
-- [REMOVED] CREATE TABLE IF NOT EXISTS → CREATE TABLE
--            이유: Oracle 21c는 IF NOT EXISTS 미지원 (23c+부터 지원)
--                 Flyway Oracle 파서가 해당 구문 파싱 불가 → Incomplete statement 오류
-- [REMOVED] 컬럼 인라인 주석(--) → Flyway Oracle 파서 안정성 확보
-- =============================================================================

-- ── 1. Outbox 이벤트 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE outbox_event (
                              id             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                              event_id       VARCHAR2(64)   NOT NULL,
                              event_type     VARCHAR2(64)   NOT NULL,
                              aggregate_type VARCHAR2(32)   NOT NULL,
                              aggregate_id   VARCHAR2(64)   NOT NULL,
                              topic          VARCHAR2(128)  NOT NULL,
                              partition_key  VARCHAR2(128)  NULL,
                              payload        CLOB           NOT NULL,
                              status         VARCHAR2(20)   DEFAULT 'NEW' NOT NULL,
                              fail_count     NUMBER(10)     DEFAULT 0 NOT NULL,
                              last_error     VARCHAR2(4000) NULL,
                              created_at     TIMESTAMP      NOT NULL,
                              published_at   TIMESTAMP      NULL,
                              CONSTRAINT pk_support_outbox_event PRIMARY KEY (id),
                              CONSTRAINT uk_support_outbox_event_id UNIQUE (event_id)
);
CREATE INDEX ix_outbox_topic_status_created ON outbox_event (topic, status, created_at);
-- [REMOVED] ix_outbox_event_id: uk_support_outbox_event_id UNIQUE(event_id)가 인덱스 자동 생성 → ORA-01408

-- ── 2. Support Outbox 이벤트 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE support_outbox_event (
                                      id             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                      event_id       VARCHAR2(64)   NOT NULL,
                                      event_type     VARCHAR2(64)   NOT NULL,
                                      aggregate_type VARCHAR2(32)   NOT NULL,
                                      aggregate_id   VARCHAR2(64)   NOT NULL,
                                      payload        CLOB           NOT NULL,
                                      dedup_key      VARCHAR2(128)  NOT NULL,
                                      status         VARCHAR2(16)   DEFAULT 'NEW' NOT NULL,
                                      retry_count    NUMBER(10)     DEFAULT 0 NOT NULL,
                                      created_at     TIMESTAMP      NOT NULL,
                                      published_at   TIMESTAMP      NULL,
                                      CONSTRAINT pk_support_outbox_event2 PRIMARY KEY (id),
                                      CONSTRAINT uk_support_outbox_dedup UNIQUE (dedup_key)
);
CREATE INDEX ix_support_outbox_status ON support_outbox_event (status, id);

-- ── 3. Kafka 중복 소비 방지 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE consumer_processed_event (
                                          id           NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                          event_id     VARCHAR2(64)   NOT NULL,
                                          processed_at TIMESTAMP      NOT NULL,
                                          CONSTRAINT pk_support_cpe PRIMARY KEY (id),
                                          CONSTRAINT uk_support_processed_event_id UNIQUE (event_id)
);

-- ── 4. 오더 상태 동기화 실패 재시도 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE order_status_sync_failure (
                                           id            NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                           order_id      NUMBER         NOT NULL,
                                           target_status VARCHAR2(30)   NOT NULL,
                                           endpoint_url  VARCHAR2(255)  NOT NULL,
                                           error_message VARCHAR2(2000) NULL,
                                           trace_id      VARCHAR2(120)  NULL,
                                           sync_status   VARCHAR2(20)   DEFAULT 'PENDING' NOT NULL,
                                           retry_count   NUMBER(10)     DEFAULT 0 NOT NULL,
                                           next_retry_at TIMESTAMP      NOT NULL,
                                           last_tried_at TIMESTAMP      NULL,
                                           succeeded_at  TIMESTAMP      NULL,
                                           created_at    TIMESTAMP      NOT NULL,
                                           updated_at    TIMESTAMP      NOT NULL,
                                           CONSTRAINT pk_order_status_sync_failure PRIMARY KEY (id)
);
CREATE INDEX idx_ossf_status_next_retry ON order_status_sync_failure (sync_status, next_retry_at);
CREATE INDEX idx_ossf_order_status      ON order_status_sync_failure (order_id, target_status);

-- ── 5. Worklist 태스크 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE support_worklist_task (
                                       worklist_task_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                       order_id          NUMBER         NOT NULL,
                                       visit_id          NUMBER         NOT NULL,
                                       category          VARCHAR2(20)   NOT NULL,
                                       primary_item_code VARCHAR2(50)   NULL,
                                       primary_item_name VARCHAR2(100)  NULL,
                                       status            VARCHAR2(20)   DEFAULT 'NEW' NOT NULL,
                                       created_at        TIMESTAMP      NOT NULL,
                                       updated_at        TIMESTAMP      NULL,
                                       CONSTRAINT pk_support_worklist_task PRIMARY KEY (worklist_task_id),
                                       CONSTRAINT uk_support_worklist_task_order UNIQUE (order_id)
);

-- ── 6. 주사 실행 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE injection_exec (
                                injection_exec_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                final_order_id    NUMBER         NOT NULL,
                                status            VARCHAR2(32)   NOT NULL,
                                note              VARCHAR2(400)  NULL,
                                idempotency_key   VARCHAR2(80)   NOT NULL,
                                created_at        TIMESTAMP      NOT NULL,
                                CONSTRAINT pk_injection_exec PRIMARY KEY (injection_exec_id),
                                CONSTRAINT uk_inj_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_inj_final_order ON injection_exec (final_order_id);

-- ── 7. 복약 실행 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE med_exec (
                          med_exec_id     NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                          final_order_id  NUMBER         NOT NULL,
                          status          VARCHAR2(32)   NOT NULL,
                          note            VARCHAR2(400)  NULL,
                          idempotency_key VARCHAR2(80)   NOT NULL,
                          created_at      TIMESTAMP      NOT NULL,
                          CONSTRAINT pk_med_exec PRIMARY KEY (med_exec_id),
                          CONSTRAINT uk_med_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_med_final_order ON med_exec (final_order_id);

-- ── 8. 내시경 리포트 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE endoscopy_report (
                                  endoscopy_report_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                  final_order_id      NUMBER         NOT NULL,
                                  status              VARCHAR2(32)   NOT NULL,
                                  report_text         VARCHAR2(2000) NOT NULL,
                                  idempotency_key     VARCHAR2(80)   NOT NULL,
                                  created_at          TIMESTAMP      NOT NULL,
                                  CONSTRAINT pk_endoscopy_report PRIMARY KEY (endoscopy_report_id),
                                  CONSTRAINT uk_endo_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_endo_final_order ON endoscopy_report (final_order_id);

-- ── 9. 검사(Lab) 결과 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE lab_result (
                            lab_result_id   NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                            order_id        NUMBER         NOT NULL,
                            result_text     CLOB           NULL,
                            status          VARCHAR2(50)   NOT NULL,
                            idempotency_key VARCHAR2(255)  NOT NULL,
                            created_at      TIMESTAMP      NOT NULL,
                            updated_at      TIMESTAMP      NULL,
                            updated_by      VARCHAR2(100)  NULL,
                            archived        NUMBER(1)      DEFAULT 0 NOT NULL,
                            archived_at     TIMESTAMP      NULL,
                            archived_by     VARCHAR2(100)  NULL,
                            archived_reason VARCHAR2(500)  NULL,
                            CONSTRAINT pk_lab_result PRIMARY KEY (lab_result_id),
                            CONSTRAINT uk_lab_idem UNIQUE (idempotency_key)
);

-- ── 10. 약국 조제 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE dispense (
                          dispense_id     NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                          order_id        NUMBER         NOT NULL,
                          dispense_text   CLOB           NULL,
                          status          VARCHAR2(50)   NOT NULL,
                          idempotency_key VARCHAR2(255)  NOT NULL,
                          created_at      TIMESTAMP      NOT NULL,
                          updated_at      TIMESTAMP      NULL,
                          updated_by      VARCHAR2(100)  NULL,
                          archived        NUMBER(1)      DEFAULT 0 NOT NULL,
                          archived_at     TIMESTAMP      NULL,
                          archived_by     VARCHAR2(100)  NULL,
                          archived_reason VARCHAR2(500)  NULL,
                          CONSTRAINT pk_dispense PRIMARY KEY (dispense_id),
                          CONSTRAINT uk_dispense_idem UNIQUE (idempotency_key)
);

-- ── 11. 시술 리포트 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE procedure_report (
                                  procedure_report_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                  order_id            NUMBER         NOT NULL,
                                  report_text         CLOB           NULL,
                                  status              VARCHAR2(50)   NOT NULL,
                                  idempotency_key     VARCHAR2(255)  NOT NULL,
                                  created_at          TIMESTAMP      NOT NULL,
                                  CONSTRAINT pk_procedure_report PRIMARY KEY (procedure_report_id),
                                  CONSTRAINT uk_proc_idem UNIQUE (idempotency_key)
);

-- ── 12. 영상(Radiology) 리포트 테이블
-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE radiology_report (
                                  radiology_report_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                  order_id            NUMBER         NOT NULL,
                                  report_text         CLOB           NULL,
                                  status              VARCHAR2(50)   NOT NULL,
                                  idempotency_key     VARCHAR2(255)  NOT NULL,
                                  created_at          TIMESTAMP      NOT NULL,
                                  updated_at          TIMESTAMP      NULL,
                                  updated_by          VARCHAR2(100)  NULL,
                                  archived            NUMBER(1)      DEFAULT 0 NOT NULL,
                                  archived_at         TIMESTAMP      NULL,
                                  archived_by         VARCHAR2(100)  NULL,
                                  archived_reason     VARCHAR2(500)  NULL,
                                  CONSTRAINT pk_radiology_report PRIMARY KEY (radiology_report_id),
                                  CONSTRAINT uk_rad_idem UNIQUE (idempotency_key)
);