-- =============================================================================
-- hospitalMSA Clinical Schema Reset SQL v1 (Oracle XE 21c / XEPDB1)
-- Target Schema: his_clinical
--
-- 근거: seed_demo_reset.sql(his_admin)만 실행하면 admin_visit은 비워지지만
--       Kafka로 동기화된 visit_clinical_status/visit_soap/order_* 는 그대로 남아
--       진료 화면 드롭다운에 유령 항목이 표시됨. clinical 스키마 별도 리셋 필요.
--
-- Usage:
--   docker cp seed_clinical_reset.sql psb-oracle:/tmp/seed_clinical_reset.sql
--   docker exec psb-oracle sqlplus his_clinical/his_password@//localhost:1521/XEPDB1 @/tmp/seed_clinical_reset.sql
-- =============================================================================

-- ============================================================
-- SECTION 1: DELETE — 하위 테이블부터 역순
-- 순서: order_item → order_header → final_order → soap_history → soap
--       → encounter_note → visit_clinical_status → outbox → processed
-- ============================================================

DELETE FROM order_item;
DELETE FROM order_header;
DELETE FROM final_order;
DELETE FROM visit_soap_history;
DELETE FROM visit_soap;
DELETE FROM encounter_note;
DELETE FROM visit_clinical_status;
DELETE FROM outbox_event;
DELETE FROM consumer_processed_event;

-- ============================================================
-- SECTION 2: IDENTITY 시퀀스 리셋
-- order_header/order_item만 IDENTITY(V1 스키마 기준).
-- visit_soap/visit_clinical_status는 PK가 visit_id(외부 참조)로 IDENTITY 아님.
-- ============================================================

ALTER TABLE order_header MODIFY order_id      GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
ALTER TABLE order_item   MODIFY order_item_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);

COMMIT;

-- ============================================================
-- SECTION 3: 검증
-- ============================================================

SELECT 'visit_clinical_status' AS tbl, COUNT(*) AS cnt FROM visit_clinical_status
UNION ALL SELECT 'visit_soap',              COUNT(*) FROM visit_soap
UNION ALL SELECT 'visit_soap_history',      COUNT(*) FROM visit_soap_history
UNION ALL SELECT 'encounter_note',          COUNT(*) FROM encounter_note
UNION ALL SELECT 'order_header',            COUNT(*) FROM order_header
UNION ALL SELECT 'order_item',              COUNT(*) FROM order_item
UNION ALL SELECT 'final_order',             COUNT(*) FROM final_order
UNION ALL SELECT 'outbox_event',            COUNT(*) FROM outbox_event
UNION ALL SELECT 'consumer_processed_event', COUNT(*) FROM consumer_processed_event;

EXIT;
