-- =============================================================================
-- hospitalMSA Demo Seed Reset SQL v3 (Oracle XE 21c / XEPDB1)
-- Target Schema: his_admin
--
-- [v3] 시드 축소: patient 5명 + admin_config만 유지.
--      reservation/appointment/visit INSERT 제거 — 발표 시연에서
--      Kafka 이벤트 체인(VISIT_REGISTERED 등)이 자연스럽게 동작하도록
--      빈 상태에서 라이브로 예약→접수→진료→오더→수납 수행.
-- [v3] IDENTITY 리셋: reservation/visit/appointment 모두 START WITH 1.
--
-- 주의: clinical 스키마(his_clinical) 리셋은 seed_clinical_reset.sql 별도 실행.
--
-- Usage:
--   docker cp seed_demo_reset.sql psb-oracle:/tmp/seed_demo_reset.sql
--   docker exec psb-oracle sqlplus his_admin/his_password@//localhost:1521/XEPDB1 @/tmp/seed_demo_reset.sql
-- =============================================================================

-- ============================================================
-- SECTION 1: DELETE — 하위 테이블부터 역순 정리
-- ============================================================

DELETE FROM admin_receipt;
DELETE FROM admin_payment;
DELETE FROM admin_payment_idempotency;
DELETE FROM admin_invoice_adjustment;
DELETE FROM admin_invoice_item;
DELETE FROM admin_invoice;
DELETE FROM admin_queue_ticket;
DELETE FROM outbox_event;
DELETE FROM consumer_processed_event;
DELETE FROM admin_reservation;
DELETE FROM admin_visit;
DELETE FROM admin_appointment;
DELETE FROM patient_alert;
DELETE FROM patient;

-- ============================================================
-- SECTION 2: IDENTITY 시퀀스 리셋
-- 시드에서 reservation/visit/appointment INSERT를 제거했으므로
-- 모두 START WITH 1 — 발표 중 라이브 등록 시 1번부터 채번
-- ============================================================

ALTER TABLE admin_reservation MODIFY reservation_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
ALTER TABLE admin_visit       MODIFY visit_id       GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
ALTER TABLE admin_appointment MODIFY appointment_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
ALTER TABLE admin_invoice     MODIFY invoice_id     GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);
ALTER TABLE admin_queue_ticket MODIFY ticket_id     GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 1);

-- ============================================================
-- SECTION 3: INSERT — patient (5명, 고정 ID)
-- ============================================================

INSERT INTO patient (patient_id, name, gender, rrn_masked, birth_date, phone, active, created_at, updated_at)
VALUES (2001, UNISTR('\BC15\C11C\C900'), 'M', '950315-1******', DATE '1995-03-15', '010-1234-5678', 1, TRUNC(SYSDATE), SYSTIMESTAMP);

INSERT INTO patient (patient_id, name, gender, rrn_masked, birth_date, phone, active, created_at, updated_at)
VALUES (2002, UNISTR('\C774\C9C0\C740'), 'F', '880722-2******', DATE '1988-07-22', '010-2345-6789', 1, TRUNC(SYSDATE), SYSTIMESTAMP);

INSERT INTO patient (patient_id, name, gender, rrn_masked, birth_date, phone, active, created_at, updated_at)
VALUES (2003, UNISTR('\AE40\BBFC\C218'), 'M', '010910-3******', DATE '2001-09-10', '010-3456-7890', 1, TRUNC(SYSDATE), SYSTIMESTAMP);

INSERT INTO patient (patient_id, name, gender, rrn_masked, birth_date, phone, active, created_at, updated_at)
VALUES (2004, UNISTR('\C815\C218\D604'), 'F', '970205-2******', DATE '1997-02-05', '010-4567-8901', 1, TRUNC(SYSDATE), SYSTIMESTAMP);

INSERT INTO patient (patient_id, name, gender, rrn_masked, birth_date, phone, active, created_at, updated_at)
VALUES (2005, UNISTR('\CD5C\C218\C9C4'), 'F', '920830-2******', DATE '1992-08-30', '010-5678-9012', 1, TRUNC(SYSDATE), SYSTIMESTAMP);

-- ============================================================
-- SECTION 4: admin_config — emergency_count (대시보드용)
-- ============================================================

MERGE INTO admin_config t
USING (SELECT 'emergency_count' AS config_key, '3' AS config_value, UNISTR('\C751\AE09 \BC31\C0C1 \C6B4\C601\C790 \C218\B3D9 \C124\C815\AC12 (0~10)') AS description FROM dual) s
ON (t.config_key = s.config_key)
WHEN MATCHED THEN
    UPDATE SET t.config_value = s.config_value, t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (config_key, config_value, description, updated_at)
    VALUES (s.config_key, s.config_value, s.description, SYSTIMESTAMP);

COMMIT;

-- ============================================================
-- SECTION 5: 검증
-- ============================================================

SELECT 'patient' AS tbl, COUNT(*) AS cnt FROM patient
UNION ALL SELECT 'admin_reservation', COUNT(*) FROM admin_reservation
UNION ALL SELECT 'admin_appointment', COUNT(*) FROM admin_appointment
UNION ALL SELECT 'admin_visit', COUNT(*) FROM admin_visit
UNION ALL SELECT 'admin_invoice', COUNT(*) FROM admin_invoice
UNION ALL SELECT 'outbox_event', COUNT(*) FROM outbox_event;

SELECT patient_id, name, phone FROM patient ORDER BY patient_id;
SELECT config_key, config_value FROM admin_config WHERE config_key = 'emergency_count';

EXIT;
