-- =============================================================================
-- Admin-Master Service Initial Schema (V1) — Oracle Edition
-- Target DB: his_admin (Oracle XE 21c 스키마)
-- [MODIFIED] AUTO_INCREMENT → GENERATED BY DEFAULT ON NULL AS IDENTITY
-- [MODIFIED] BIGINT → NUMBER, INT → NUMBER(10), TINYINT(1) → NUMBER(1)
-- [MODIFIED] VARCHAR(n) → VARCHAR2(n)
-- [MODIFIED] DATETIME → TIMESTAMP
-- [MODIFIED] LONGTEXT / TEXT → CLOB
-- [MODIFIED] TIME → INTERVAL DAY TO SECOND (Oracle TIME 미지원)
-- [MODIFIED] DEFAULT CURRENT_TIMESTAMP → DEFAULT SYSTIMESTAMP
-- [REMOVED] ENGINE=InnoDB, DEFAULT CHARSET, COLLATE
-- [REMOVED] KEY (인덱스) → CREATE INDEX 별도 선언
-- [REMOVED] CREATE TABLE IF NOT EXISTS → CREATE TABLE
--            이유: Oracle 21c는 IF NOT EXISTS 미지원 (23c+부터 지원)
--                 Flyway Oracle 파서가 해당 구문 파싱 불가 → Incomplete statement 오류
-- [REMOVED] 컬럼 인라인 주석(--) → Flyway Oracle 파서 안정성 확보
-- =============================================================================

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admission_exec (
                                admission_exec_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                final_order_id    NUMBER         NOT NULL,
                                ward              VARCHAR2(64)   NOT NULL,
                                status            VARCHAR2(32)   NOT NULL,
                                idempotency_key   VARCHAR2(80)   NOT NULL,
                                admitted_at       TIMESTAMP      NULL,
                                discharged_at     TIMESTAMP      NULL,
                                updated_at        TIMESTAMP      NULL,
                                created_at        TIMESTAMP      NOT NULL,
                                CONSTRAINT pk_admission_exec PRIMARY KEY (admission_exec_id),
                                CONSTRAINT uk_admission_exec_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_adm_final_order ON admission_exec (final_order_id);
-- [REMOVED] idx_adm_idem 제거: uk_admission_exec_idem UNIQUE constraint가 동일 컬럼 인덱스 자동 생성 → ORA-01408

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE surgery_exec (
                              surgery_exec_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                              final_order_id  NUMBER         NOT NULL,
                              surgery_name    VARCHAR2(128)  NOT NULL,
                              room            VARCHAR2(64)   NULL,
                              surgeon         VARCHAR2(80)   NULL,
                              status          VARCHAR2(32)   NOT NULL,
                              scheduled_at    TIMESTAMP      NULL,
                              completed_at    TIMESTAMP      NULL,
                              updated_at      TIMESTAMP      NULL,
                              idempotency_key VARCHAR2(80)   NOT NULL,
                              created_at      TIMESTAMP      NOT NULL,
                              CONSTRAINT pk_surgery_exec PRIMARY KEY (surgery_exec_id),
                              CONSTRAINT uk_surgery_exec_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_surg_final_order ON surgery_exec (final_order_id);
-- [REMOVED] idx_surg_idem 제거: uk_surgery_exec_idem UNIQUE constraint가 동일 컬럼 인덱스 자동 생성 → ORA-01408

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_appointment (
                                   appointment_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                   patient_id      NUMBER         NULL,
                                   patient_name    VARCHAR2(255)  NULL,
                                   department_code VARCHAR2(255)  NULL,
                                   doctor_id       VARCHAR2(255)  NULL,
                                   status          VARCHAR2(255)  NULL,
                                   scheduled_at    TIMESTAMP      NULL,
                                   created_at      TIMESTAMP      NULL,
                                   updated_at      TIMESTAMP      NULL,
                                   CONSTRAINT pk_admin_appointment PRIMARY KEY (appointment_id)
);
CREATE INDEX idx_admin_appt_scheduled ON admin_appointment (scheduled_at);
CREATE INDEX idx_admin_appt_status    ON admin_appointment (status);
CREATE INDEX idx_admin_appt_patient   ON admin_appointment (patient_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_visit (
                             visit_id        NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                             patient_id      NUMBER         NULL,
                             patient_name    VARCHAR2(255)  NULL,
                             department_code VARCHAR2(255)  NULL,
                             doctor_id       VARCHAR2(255)  NULL,
                             status          VARCHAR2(255)  NULL,
                             arrival_type    VARCHAR2(20)   NULL,
                             triage_level    NUMBER(10)     NULL,
                             created_at      TIMESTAMP      NULL,
                             updated_at      TIMESTAMP      NULL,
                             canceled_at     TIMESTAMP      NULL,
                             cancel_reason   VARCHAR2(255)  NULL,
                             closed_at       TIMESTAMP      NULL,
                             CONSTRAINT pk_admin_visit PRIMARY KEY (visit_id)
);
CREATE INDEX idx_admin_visit_status         ON admin_visit (status);
CREATE INDEX idx_admin_visit_patient        ON admin_visit (patient_id);
CREATE INDEX idx_admin_visit_arrival_type   ON admin_visit (arrival_type);
CREATE INDEX idx_admin_visit_triage_level   ON admin_visit (triage_level);
CREATE INDEX idx_admin_visit_status_created ON admin_visit (status, created_at);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_reservation (
                                   reservation_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                   patient_id      NUMBER         NULL,
                                   patient_name    VARCHAR2(255)  NULL,
                                   department_code VARCHAR2(255)  NULL,
                                   doctor_id       VARCHAR2(255)  NULL,
                                   scheduled_at    TIMESTAMP      NULL,
                                   status          VARCHAR2(255)  NULL,
                                   created_at      TIMESTAMP      NULL,
                                   updated_at      TIMESTAMP      NULL,
                                   canceled_at     TIMESTAMP      NULL,
                                   cancel_reason   VARCHAR2(255)  NULL,
                                   visit_id        NUMBER         NULL,
                                   CONSTRAINT pk_admin_reservation PRIMARY KEY (reservation_id)
);
CREATE INDEX idx_admin_resv_status    ON admin_reservation (status);
CREATE INDEX idx_admin_resv_scheduled ON admin_reservation (scheduled_at);
CREATE INDEX idx_admin_resv_patient   ON admin_reservation (patient_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_queue_ticket (
                                    ticket_id     NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                    visit_id      NUMBER         NULL,
                                    category      VARCHAR2(255)  NULL,
                                    ticket_no     VARCHAR2(255)  NULL,
                                    status        VARCHAR2(255)  NULL,
                                    issued_at     TIMESTAMP      NULL,
                                    called_at     TIMESTAMP      NULL,
                                    done_at       TIMESTAMP      NULL,
                                    last_event_id VARCHAR2(255)  NULL,
                                    CONSTRAINT pk_admin_queue_ticket PRIMARY KEY (ticket_id)
);
CREATE INDEX idx_admin_queue_status   ON admin_queue_ticket (status);
CREATE INDEX idx_admin_queue_visit    ON admin_queue_ticket (visit_id);
CREATE INDEX idx_admin_queue_category ON admin_queue_ticket (category);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_invoice (
                               invoice_id   NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                               visit_id     NUMBER         NULL,
                               status       VARCHAR2(255)  NULL,
                               total_amount NUMBER         NULL,
                               created_at   TIMESTAMP      NULL,
                               updated_at   TIMESTAMP      NULL,
                               CONSTRAINT pk_admin_invoice PRIMARY KEY (invoice_id)
);
CREATE INDEX idx_admin_invoice_visit        ON admin_invoice (visit_id);
CREATE INDEX idx_admin_invoice_status       ON admin_invoice (status);
CREATE INDEX idx_admin_invoice_visit_status ON admin_invoice (visit_id, status);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_invoice_item (
                                    invoice_item_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                    invoice_id      NUMBER         NULL,
                                    item_code       VARCHAR2(255)  NULL,
                                    item_name       VARCHAR2(255)  NULL,
                                    unit_price      NUMBER         NULL,
                                    qty             NUMBER(10)     NULL,
                                    line_total      NUMBER         NULL,
                                    CONSTRAINT pk_admin_invoice_item PRIMARY KEY (invoice_item_id)
);
CREATE INDEX idx_admin_invoice_item_invoice ON admin_invoice_item (invoice_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_invoice_adjustment (
                                          adjustment_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                          invoice_id    NUMBER         NULL,
                                          type          VARCHAR2(255)  NULL,
                                          old_amount    NUMBER(10)     NULL,
                                          new_amount    NUMBER(10)     NULL,
                                          reason        VARCHAR2(255)  NULL,
                                          created_at    TIMESTAMP      NULL,
                                          CONSTRAINT pk_admin_invoice_adjustment PRIMARY KEY (adjustment_id)
);
CREATE INDEX idx_inv_adj_invoice ON admin_invoice_adjustment (invoice_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_payment (
                               payment_id      NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                               invoice_id      NUMBER         NULL,
                               method          VARCHAR2(255)  NULL,
                               amount          NUMBER         NULL,
                               status          VARCHAR2(255)  NULL,
                               idempotency_key VARCHAR2(255)  NULL,
                               paid_at         TIMESTAMP      NULL,
                               CONSTRAINT pk_admin_payment PRIMARY KEY (payment_id),
                               CONSTRAINT uk_admin_payment_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_admin_payment_invoice        ON admin_payment (invoice_id);
-- [REMOVED] idx_admin_payment_idem 제거: uk_admin_payment_idem UNIQUE constraint가 동일 컬럼 인덱스 자동 생성 → ORA-01408
CREATE INDEX idx_admin_payment_invoice_status ON admin_payment (invoice_id, status);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_receipt (
                               receipt_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                               payment_id NUMBER         NULL,
                               receipt_no VARCHAR2(255)  NULL,
                               created_at TIMESTAMP      NULL,
                               CONSTRAINT pk_admin_receipt PRIMARY KEY (receipt_id)
);
CREATE INDEX idx_admin_receipt_payment ON admin_receipt (payment_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE admin_payment_idempotency (
                                           idem_key       VARCHAR2(120) NOT NULL,
                                           invoice_id     NUMBER        NULL,
                                           payment_id     NUMBER        NULL,
                                           request_amount NUMBER        NULL,
                                           request_method VARCHAR2(30)  NULL,
                                           status         VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
                                           created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
                                           completed_at   TIMESTAMP     NULL,
                                           CONSTRAINT pk_admin_pay_idem PRIMARY KEY (idem_key)
);
CREATE INDEX idx_admin_pay_idem_invoice ON admin_payment_idempotency (invoice_id);
CREATE INDEX idx_admin_pay_idem_payment ON admin_payment_idempotency (payment_id);
CREATE INDEX idx_admin_pay_idem_status  ON admin_payment_idempotency (status);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE code_set (
                          code_set_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                          code_set_key VARCHAR2(50)   NOT NULL,
                          name         VARCHAR2(100)  NOT NULL,
                          active       NUMBER(1)      DEFAULT 1 NOT NULL,
                          CONSTRAINT pk_code_set PRIMARY KEY (code_set_id),
                          CONSTRAINT uk_code_set_key UNIQUE (code_set_key)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE code_item (
                           code_item_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                           code_set_id  NUMBER         NOT NULL,
                           code         VARCHAR2(50)   NOT NULL,
                           name         VARCHAR2(100)  NOT NULL,
                           active       NUMBER(1)      DEFAULT 1 NOT NULL,
                           sort_order   NUMBER(10)     DEFAULT 0 NOT NULL,
                           CONSTRAINT pk_code_item PRIMARY KEY (code_item_id),
                           CONSTRAINT fk_code_item_code_set FOREIGN KEY (code_set_id) REFERENCES code_set(code_set_id)
);
CREATE INDEX idx_code_item_code_set_id ON code_item (code_set_id);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE department (
                            department_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                            code          VARCHAR2(50)   NOT NULL,
                            name          VARCHAR2(100)  NOT NULL,
                            active        NUMBER(1)      DEFAULT 1 NOT NULL,
                            CONSTRAINT pk_department PRIMARY KEY (department_id),
                            CONSTRAINT uk_department_code UNIQUE (code)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE master_exam_catalog (
                                     exam_catalog_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                     item_code       VARCHAR2(50)   NOT NULL,
                                     category        VARCHAR2(20)   NOT NULL,
                                     display_name_kr VARCHAR2(100)  NOT NULL,
                                     active          NUMBER(1)      DEFAULT 1 NOT NULL,
                                     created_at      TIMESTAMP      NOT NULL,
                                     updated_at      TIMESTAMP      NULL,
                                     CONSTRAINT pk_master_exam_catalog PRIMARY KEY (exam_catalog_id),
                                     CONSTRAINT uk_master_exam_catalog_code UNIQUE (item_code)
);

-- [MODIFIED] IF NOT EXISTS 제거
-- patient_id: IDENTITY 없이 명시값 삽입 (MySQL 동일 패턴 유지)
CREATE TABLE patient (
                         patient_id NUMBER         NOT NULL,
                         name       VARCHAR2(255)  NOT NULL,
                         gender     VARCHAR2(255)  NOT NULL,
                         rrn_masked VARCHAR2(255)  NULL,
                         birth_date DATE           NULL,
                         phone      VARCHAR2(255)  NULL,
                         active     NUMBER(1)      NOT NULL,
                         created_at TIMESTAMP      NULL,
                         updated_at TIMESTAMP      NULL,
                         CONSTRAINT pk_patient PRIMARY KEY (patient_id)
);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE patient_alert (
                               patient_alert_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                               patient_id       NUMBER         NOT NULL,
                               type             VARCHAR2(255)  NOT NULL,
                               message          VARCHAR2(255)  NOT NULL,
                               active           NUMBER(1)      NOT NULL,
                               created_at       TIMESTAMP      NULL,
                               updated_at       TIMESTAMP      NULL,
                               CONSTRAINT pk_patient_alert PRIMARY KEY (patient_alert_id)
);
CREATE INDEX idx_patient_alert_patient ON patient_alert (patient_id);
CREATE INDEX idx_patient_alert_active  ON patient_alert (active);

-- [MODIFIED] IF NOT EXISTS 제거
-- start_time / end_time: INTERVAL DAY(0) TO SECOND(0) (Oracle TIME 미지원)
CREATE TABLE doctor_schedule_template (
                                          schedule_template_id NUMBER                        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                          staff_profile_id     NUMBER                        NOT NULL,
                                          day_of_week          NUMBER(10)                    NOT NULL,
                                          start_time           INTERVAL DAY(0) TO SECOND(0) NOT NULL,
                                          end_time             INTERVAL DAY(0) TO SECOND(0) NOT NULL,
                                          slot_minutes         NUMBER(10)                    NOT NULL,
                                          active               NUMBER(1)                     DEFAULT 1 NOT NULL,
                                          note                 VARCHAR2(200)                 NULL,
                                          CONSTRAINT pk_doctor_schedule_template PRIMARY KEY (schedule_template_id)
);
CREATE INDEX idx_dst_staff_day ON doctor_schedule_template (staff_profile_id, day_of_week);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE staff_profile (
                               staff_profile_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                               login_id         VARCHAR2(50)   NOT NULL,
                               name             VARCHAR2(100)  NOT NULL,
                               job_type         VARCHAR2(50)   NOT NULL,
                               department_id    NUMBER         NULL,
                               phone            VARCHAR2(20)   NULL,
                               email            VARCHAR2(150)  NULL,
                               active           NUMBER(1)      DEFAULT 1 NOT NULL,
                               CONSTRAINT pk_staff_profile PRIMARY KEY (staff_profile_id),
                               CONSTRAINT uk_staff_profile_login_id UNIQUE (login_id)
);
CREATE INDEX idx_staff_profile_phone ON staff_profile (phone);
CREATE INDEX idx_staff_profile_email ON staff_profile (email);

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE outbox_event (
                              id             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                              event_id       VARCHAR2(64)   NOT NULL,
                              event_type     VARCHAR2(64)   NOT NULL,
                              aggregate_type VARCHAR2(32)   NOT NULL,
                              aggregate_id   VARCHAR2(64)   NOT NULL,
                              topic          VARCHAR2(128)  NOT NULL,
                              partition_key  VARCHAR2(128)  NULL,
                              payload        CLOB           NOT NULL,
                              status         VARCHAR2(20)   NOT NULL,
                              fail_count     NUMBER(10)     NOT NULL,
                              last_error     VARCHAR2(4000) NULL,
                              created_at     TIMESTAMP      NOT NULL,
                              published_at   TIMESTAMP      NULL,
                              CONSTRAINT pk_outbox_event PRIMARY KEY (id),
                              CONSTRAINT uk_outbox_event_id UNIQUE (event_id)
);
CREATE INDEX ix_outbox_topic_status_created ON outbox_event (topic, status, created_at);
-- [REMOVED] ix_outbox_event_id 제거: uk_outbox_event_id UNIQUE constraint가 동일 컬럼 인덱스 자동 생성 → ORA-01408

-- [MODIFIED] IF NOT EXISTS 제거
CREATE TABLE consumer_processed_event (
                                          id           NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
                                          event_id     VARCHAR2(64)   NOT NULL,
                                          processed_at TIMESTAMP      NOT NULL,
                                          CONSTRAINT pk_consumer_processed_event PRIMARY KEY (id),
                                          CONSTRAINT uk_processed_event_id UNIQUE (event_id)
);