-- =============================================================================
-- Admin-Master Service — V1 통합 (Oracle Edition)
-- 구성: 스키마 DDL + 전체 시드 데이터 (V1~V4 통합)
-- Target DB: his_admin (Oracle XE 21c / XEPDB1)
-- Oracle 규칙:
--   GENERATED BY DEFAULT ON NULL AS IDENTITY (명시적 ID INSERT 허용)
--   CREATE TABLE IF NOT EXISTS 미지원 → CREATE TABLE
--   BOOLEAN 미지원 → NUMBER(1)
--   TIME 미지원 → INTERVAL DAY TO SECOND
--   MERGE INTO (INSERT IGNORE/ON DUPLICATE KEY 대체)
--   TRUNC(SYSDATE): 매 기동 시 오늘 날짜로 갱신 (시드 날짜 필터 통과용)
-- =============================================================================

-- ============================================================
-- SECTION 1: DDL — 테이블 생성
-- ============================================================

CREATE TABLE admission_exec (
    admission_exec_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    final_order_id    NUMBER         NOT NULL,
    ward              VARCHAR2(64)   NOT NULL,
    status            VARCHAR2(32)   NOT NULL,
    idempotency_key   VARCHAR2(80)   NOT NULL,
    admitted_at       TIMESTAMP      NULL,
    discharged_at     TIMESTAMP      NULL,
    updated_at        TIMESTAMP      NULL,
    created_at        TIMESTAMP      NOT NULL,
    CONSTRAINT pk_admission_exec PRIMARY KEY (admission_exec_id),
    CONSTRAINT uk_admission_exec_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_adm_final_order ON admission_exec (final_order_id);

CREATE TABLE surgery_exec (
    surgery_exec_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    final_order_id  NUMBER         NOT NULL,
    surgery_name    VARCHAR2(128)  NOT NULL,
    room            VARCHAR2(64)   NULL,
    surgeon         VARCHAR2(80)   NULL,
    status          VARCHAR2(32)   NOT NULL,
    scheduled_at    TIMESTAMP      NULL,
    completed_at    TIMESTAMP      NULL,
    updated_at      TIMESTAMP      NULL,
    idempotency_key VARCHAR2(80)   NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    CONSTRAINT pk_surgery_exec PRIMARY KEY (surgery_exec_id),
    CONSTRAINT uk_surgery_exec_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_surg_final_order ON surgery_exec (final_order_id);

CREATE TABLE admin_appointment (
    appointment_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    patient_id      NUMBER         NULL,
    patient_name    VARCHAR2(255)  NULL,
    department_code VARCHAR2(255)  NULL,
    doctor_id       VARCHAR2(255)  NULL,
    status          VARCHAR2(255)  NULL,
    scheduled_at    TIMESTAMP      NULL,
    created_at      TIMESTAMP      NULL,
    updated_at      TIMESTAMP      NULL,
    CONSTRAINT pk_admin_appointment PRIMARY KEY (appointment_id)
);
CREATE INDEX idx_admin_appt_scheduled ON admin_appointment (scheduled_at);
CREATE INDEX idx_admin_appt_status    ON admin_appointment (status);
CREATE INDEX idx_admin_appt_patient   ON admin_appointment (patient_id);

CREATE TABLE admin_visit (
    visit_id        NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    patient_id      NUMBER         NULL,
    patient_name    VARCHAR2(255)  NULL,
    department_code VARCHAR2(255)  NULL,
    doctor_id       VARCHAR2(255)  NULL,
    status          VARCHAR2(255)  NULL,
    arrival_type    VARCHAR2(20)   NULL,
    triage_level    NUMBER(10)     NULL,
    created_at      TIMESTAMP      NULL,
    updated_at      TIMESTAMP      NULL,
    canceled_at     TIMESTAMP      NULL,
    cancel_reason   VARCHAR2(255)  NULL,
    closed_at       TIMESTAMP      NULL,
    CONSTRAINT pk_admin_visit PRIMARY KEY (visit_id)
);
CREATE INDEX idx_admin_visit_status         ON admin_visit (status);
CREATE INDEX idx_admin_visit_patient        ON admin_visit (patient_id);
CREATE INDEX idx_admin_visit_arrival_type   ON admin_visit (arrival_type);
CREATE INDEX idx_admin_visit_triage_level   ON admin_visit (triage_level);
CREATE INDEX idx_admin_visit_status_created ON admin_visit (status, created_at);

CREATE TABLE admin_reservation (
    reservation_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    patient_id      NUMBER         NULL,
    patient_name    VARCHAR2(255)  NULL,
    department_code VARCHAR2(255)  NULL,
    doctor_id       VARCHAR2(255)  NULL,
    scheduled_at    TIMESTAMP      NULL,
    status          VARCHAR2(255)  NULL,
    created_at      TIMESTAMP      NULL,
    updated_at      TIMESTAMP      NULL,
    canceled_at     TIMESTAMP      NULL,
    cancel_reason   VARCHAR2(255)  NULL,
    visit_id        NUMBER         NULL,
    CONSTRAINT pk_admin_reservation PRIMARY KEY (reservation_id)
);
CREATE INDEX idx_admin_resv_status    ON admin_reservation (status);
CREATE INDEX idx_admin_resv_scheduled ON admin_reservation (scheduled_at);
CREATE INDEX idx_admin_resv_patient   ON admin_reservation (patient_id);

CREATE TABLE admin_queue_ticket (
    ticket_id     NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    visit_id      NUMBER         NULL,
    category      VARCHAR2(255)  NULL,
    ticket_no     VARCHAR2(255)  NULL,
    status        VARCHAR2(255)  NULL,
    issued_at     TIMESTAMP      NULL,
    called_at     TIMESTAMP      NULL,
    done_at       TIMESTAMP      NULL,
    last_event_id VARCHAR2(255)  NULL,
    CONSTRAINT pk_admin_queue_ticket PRIMARY KEY (ticket_id)
);
CREATE INDEX idx_admin_queue_status   ON admin_queue_ticket (status);
CREATE INDEX idx_admin_queue_visit    ON admin_queue_ticket (visit_id);
CREATE INDEX idx_admin_queue_category ON admin_queue_ticket (category);

CREATE TABLE admin_invoice (
    invoice_id   NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    visit_id     NUMBER         NULL,
    status       VARCHAR2(255)  NULL,
    total_amount NUMBER         NULL,
    created_at   TIMESTAMP      NULL,
    updated_at   TIMESTAMP      NULL,
    CONSTRAINT pk_admin_invoice PRIMARY KEY (invoice_id)
);
CREATE INDEX idx_admin_invoice_visit        ON admin_invoice (visit_id);
CREATE INDEX idx_admin_invoice_status       ON admin_invoice (status);
CREATE INDEX idx_admin_invoice_visit_status ON admin_invoice (visit_id, status);

CREATE TABLE admin_invoice_item (
    invoice_item_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    invoice_id      NUMBER         NULL,
    item_code       VARCHAR2(255)  NULL,
    item_name       VARCHAR2(255)  NULL,
    unit_price      NUMBER         NULL,
    qty             NUMBER(10)     NULL,
    line_total      NUMBER         NULL,
    CONSTRAINT pk_admin_invoice_item PRIMARY KEY (invoice_item_id)
);
CREATE INDEX idx_admin_invoice_item_invoice ON admin_invoice_item (invoice_id);

CREATE TABLE admin_invoice_adjustment (
    adjustment_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    invoice_id    NUMBER         NULL,
    type          VARCHAR2(255)  NULL,
    old_amount    NUMBER(10)     NULL,
    new_amount    NUMBER(10)     NULL,
    reason        VARCHAR2(255)  NULL,
    created_at    TIMESTAMP      NULL,
    CONSTRAINT pk_admin_invoice_adjustment PRIMARY KEY (adjustment_id)
);
CREATE INDEX idx_inv_adj_invoice ON admin_invoice_adjustment (invoice_id);

CREATE TABLE admin_payment (
    payment_id      NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    invoice_id      NUMBER         NULL,
    method          VARCHAR2(255)  NULL,
    amount          NUMBER         NULL,
    status          VARCHAR2(255)  NULL,
    idempotency_key VARCHAR2(255)  NULL,
    paid_at         TIMESTAMP      NULL,
    CONSTRAINT pk_admin_payment PRIMARY KEY (payment_id),
    CONSTRAINT uk_admin_payment_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_admin_payment_invoice        ON admin_payment (invoice_id);
CREATE INDEX idx_admin_payment_invoice_status ON admin_payment (invoice_id, status);

CREATE TABLE admin_receipt (
    receipt_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    payment_id NUMBER         NULL,
    receipt_no VARCHAR2(255)  NULL,
    created_at TIMESTAMP      NULL,
    CONSTRAINT pk_admin_receipt PRIMARY KEY (receipt_id)
);
CREATE INDEX idx_admin_receipt_payment ON admin_receipt (payment_id);

CREATE TABLE admin_payment_idempotency (
    idem_key       VARCHAR2(120) NOT NULL,
    invoice_id     NUMBER        NULL,
    payment_id     NUMBER        NULL,
    request_amount NUMBER        NULL,
    request_method VARCHAR2(30)  NULL,
    status         VARCHAR2(20)  DEFAULT 'PENDING' NOT NULL,
    created_at     TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    completed_at   TIMESTAMP     NULL,
    CONSTRAINT pk_admin_pay_idem PRIMARY KEY (idem_key)
);
CREATE INDEX idx_admin_pay_idem_invoice ON admin_payment_idempotency (invoice_id);
CREATE INDEX idx_admin_pay_idem_payment ON admin_payment_idempotency (payment_id);
CREATE INDEX idx_admin_pay_idem_status  ON admin_payment_idempotency (status);

CREATE TABLE code_set (
    code_set_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    code_set_key VARCHAR2(50)   NOT NULL,
    name         VARCHAR2(100)  NOT NULL,
    active       NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT pk_code_set PRIMARY KEY (code_set_id),
    CONSTRAINT uk_code_set_key UNIQUE (code_set_key)
);

CREATE TABLE code_item (
    code_item_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    code_set_id  NUMBER         NOT NULL,
    code         VARCHAR2(50)   NOT NULL,
    name         VARCHAR2(100)  NOT NULL,
    active       NUMBER(1)      DEFAULT 1 NOT NULL,
    sort_order   NUMBER(10)     DEFAULT 0 NOT NULL,
    CONSTRAINT pk_code_item PRIMARY KEY (code_item_id),
    CONSTRAINT fk_code_item_code_set FOREIGN KEY (code_set_id) REFERENCES code_set(code_set_id)
);
CREATE INDEX idx_code_item_code_set_id ON code_item (code_set_id);

CREATE TABLE department (
    department_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    code          VARCHAR2(50)   NOT NULL,
    name          VARCHAR2(100)  NOT NULL,
    active        NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uk_department_code UNIQUE (code)
);

CREATE TABLE master_exam_catalog (
    exam_catalog_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    item_code       VARCHAR2(50)   NOT NULL,
    category        VARCHAR2(20)   NOT NULL,
    display_name_kr VARCHAR2(100)  NOT NULL,
    active          NUMBER(1)      DEFAULT 1 NOT NULL,
    created_at      TIMESTAMP      NOT NULL,
    updated_at      TIMESTAMP      NULL,
    CONSTRAINT pk_master_exam_catalog PRIMARY KEY (exam_catalog_id),
    CONSTRAINT uk_master_exam_catalog_code UNIQUE (item_code)
);

CREATE TABLE patient (
    patient_id NUMBER         NOT NULL,
    name       VARCHAR2(255)  NOT NULL,
    gender     VARCHAR2(255)  NOT NULL,
    rrn_masked VARCHAR2(255)  NULL,
    birth_date DATE           NULL,
    phone      VARCHAR2(255)  NULL,
    active     NUMBER(1)      NOT NULL,
    created_at TIMESTAMP      NULL,
    updated_at TIMESTAMP      NULL,
    CONSTRAINT pk_patient PRIMARY KEY (patient_id)
);

CREATE TABLE patient_alert (
    patient_alert_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    patient_id       NUMBER         NOT NULL,
    type             VARCHAR2(255)  NOT NULL,
    message          VARCHAR2(255)  NOT NULL,
    active           NUMBER(1)      NOT NULL,
    created_at       TIMESTAMP      NULL,
    updated_at       TIMESTAMP      NULL,
    CONSTRAINT pk_patient_alert PRIMARY KEY (patient_alert_id)
);
CREATE INDEX idx_patient_alert_patient ON patient_alert (patient_id);
CREATE INDEX idx_patient_alert_active  ON patient_alert (active);

CREATE TABLE doctor_schedule_template (
    schedule_template_id NUMBER                        GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    staff_profile_id     NUMBER                        NOT NULL,
    day_of_week          NUMBER(10)                    NOT NULL,
    start_time           INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    end_time             INTERVAL DAY(0) TO SECOND(0) NOT NULL,
    slot_minutes         NUMBER(10)                    NOT NULL,
    active               NUMBER(1)                     DEFAULT 1 NOT NULL,
    note                 VARCHAR2(200)                 NULL,
    CONSTRAINT pk_doctor_schedule_template PRIMARY KEY (schedule_template_id)
);
CREATE INDEX idx_dst_staff_day ON doctor_schedule_template (staff_profile_id, day_of_week);

CREATE TABLE staff_profile (
    staff_profile_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    login_id         VARCHAR2(50)   NOT NULL,
    name             VARCHAR2(100)  NOT NULL,
    job_type         VARCHAR2(50)   NOT NULL,
    department_id    NUMBER         NULL,
    phone            VARCHAR2(20)   NULL,
    email            VARCHAR2(150)  NULL,
    active           NUMBER(1)      DEFAULT 1 NOT NULL,
    CONSTRAINT pk_staff_profile PRIMARY KEY (staff_profile_id),
    CONSTRAINT uk_staff_profile_login_id UNIQUE (login_id)
);
CREATE INDEX idx_staff_profile_phone ON staff_profile (phone);
CREATE INDEX idx_staff_profile_email ON staff_profile (email);

CREATE TABLE outbox_event (
    id             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    event_id       VARCHAR2(64)   NOT NULL,
    event_type     VARCHAR2(64)   NOT NULL,
    aggregate_type VARCHAR2(32)   NOT NULL,
    aggregate_id   VARCHAR2(64)   NOT NULL,
    topic          VARCHAR2(128)  NOT NULL,
    partition_key  VARCHAR2(128)  NULL,
    payload        CLOB           NOT NULL,
    status         VARCHAR2(20)   NOT NULL,
    fail_count     NUMBER(10)     NOT NULL,
    last_error     VARCHAR2(4000) NULL,
    created_at     TIMESTAMP      NOT NULL,
    published_at   TIMESTAMP      NULL,
    CONSTRAINT pk_outbox_event PRIMARY KEY (id),
    CONSTRAINT uk_outbox_event_id UNIQUE (event_id)
);
CREATE INDEX ix_outbox_topic_status_created ON outbox_event (topic, status, created_at);

CREATE TABLE consumer_processed_event (
    id           NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    event_id     VARCHAR2(64)   NOT NULL,
    processed_at TIMESTAMP      NOT NULL,
    CONSTRAINT pk_consumer_processed_event PRIMARY KEY (id),
    CONSTRAINT uk_processed_event_id UNIQUE (event_id)
);

-- [통합 V4] admin_config: 운영자 수동 설정값 테이블
CREATE TABLE admin_config (
    config_key   VARCHAR2(100) NOT NULL,
    config_value VARCHAR2(500) NOT NULL,
    description  VARCHAR2(500) NULL,
    updated_at   TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT pk_admin_config PRIMARY KEY (config_key)
);

-- ============================================================
-- SECTION 2: SEED — 기준 데이터
-- ============================================================

-- ── department ──────────────────────────────────────────────
MERGE INTO department t
USING (
    SELECT 1 AS department_id, 'INTERNAL'  AS code, UNISTR('\B0B4\AC00')      AS name, 1 AS active FROM dual UNION ALL
    SELECT 2,                   'SURGERY',            UNISTR('\C678\AC00'),               1             FROM dual UNION ALL
    SELECT 3,                   'RADIOLOGY',          UNISTR('\C601\C0C1\C758\D559\AC00'), 1             FROM dual
) s ON (t.code = s.code)
WHEN MATCHED THEN
    UPDATE SET t.name = s.name, t.active = s.active
WHEN NOT MATCHED THEN
    INSERT (code, name, active) VALUES (s.code, s.name, s.active);

-- ── staff_profile ────────────────────────────────────────────
DELETE FROM staff_profile WHERE staff_profile_id >= 6;

MERGE INTO staff_profile t
USING (
    SELECT 1 AS staff_profile_id, 'lee.doctor'  AS login_id, UNISTR('\C774\C21C\C2E0')   AS name, 'DOCTOR' AS job_type, 1 AS department_id, '010-1111-1111' AS phone, 'lee@hospital.local'  AS email, 1 AS active FROM dual UNION ALL
    SELECT 2,                      'kim.doctor',               UNISTR('\AE40\C2DC\BBFC'),             'DOCTOR',            2,                  '010-2222-2222',           'kim@hospital.local',             1             FROM dual UNION ALL
    SELECT 3,                      'park.doctor',              UNISTR('\BC15\D601\AC70\C138'),         'DOCTOR',            3,                  '010-3333-3333',           'park@hospital.local',            1             FROM dual UNION ALL
    SELECT 4,                      'adm1',                     UNISTR('\C6D0\BB341'),                  'ADMIN',             NULL,               '010-4444-4444',           'adm1@hospital.local',            1             FROM dual UNION ALL
    SELECT 5,                      'adm2',                     UNISTR('\C6D0\BB342'),                  'ADMIN',             NULL,               '010-5555-5555',           'adm2@hospital.local',            1             FROM dual
) s ON (t.staff_profile_id = s.staff_profile_id)
WHEN MATCHED THEN
    UPDATE SET t.login_id = s.login_id, t.name = s.name, t.job_type = s.job_type,
               t.department_id = s.department_id, t.phone = s.phone, t.email = s.email, t.active = s.active
WHEN NOT MATCHED THEN
    INSERT (staff_profile_id, login_id, name, job_type, department_id, phone, email, active)
    VALUES (s.staff_profile_id, s.login_id, s.name, s.job_type, s.department_id, s.phone, s.email, s.active);

-- ── admin_visit ──────────────────────────────────────────────
-- TRUNC(SYSDATE): 매 기동 시 오늘 날짜로 갱신 → Dashboard date 필터 통과
MERGE INTO admin_visit t
USING (
    SELECT 11001 AS visit_id, 2001 AS patient_id, UNISTR('\BC15\C11C\C900') AS patient_name, 'INTERNAL' AS department_code, 'lee.doctor'  AS doctor_id, 'WAITING'      AS status, NULL        AS arrival_type, NULL AS triage_level FROM dual UNION ALL
    SELECT 11002,             2001,                UNISTR('\BC15\C11C\C900'),                  'INTERNAL',                   'lee.doctor',               'IN_TREATMENT',            NULL,                       NULL              FROM dual UNION ALL
    SELECT 11003,             2002,                UNISTR('\C774\C9C0\C740'),                  'INTERNAL',                   'kim.doctor',               'WAITING',                 NULL,                       NULL              FROM dual UNION ALL
    SELECT 11004,             2003,                UNISTR('\AE40\BBFC\C218'),                  'INTERNAL',                   'park.doctor',              'COMPLETED',               NULL,                       NULL              FROM dual UNION ALL
    SELECT 11005,             2002,                UNISTR('\C774\C9C0\C740'),                  'INTERNAL',                   'kim.doctor',               'WAITING',                 'EMERGENCY',                1                 FROM dual UNION ALL
    SELECT 11006,             2002,                UNISTR('\C774\C9C0\C740'),                  'INTERNAL',                   'park.doctor',              'WAITING',                 NULL,                       NULL              FROM dual
) s ON (t.visit_id = s.visit_id)
WHEN MATCHED THEN
    UPDATE SET t.patient_id = s.patient_id, t.patient_name = s.patient_name,
               t.department_code = s.department_code, t.doctor_id = s.doctor_id,
               t.status = s.status, t.arrival_type = s.arrival_type,
               t.triage_level = s.triage_level,
               t.created_at = TRUNC(SYSDATE), t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (visit_id, patient_id, patient_name, department_code, doctor_id, status, arrival_type, triage_level, created_at, updated_at)
    VALUES (s.visit_id, s.patient_id, s.patient_name, s.department_code, s.doctor_id, s.status, s.arrival_type, s.triage_level, TRUNC(SYSDATE), SYSTIMESTAMP);

-- ── admin_appointment (Dashboard 예약 집계용) ────────────────
MERGE INTO admin_appointment t
USING (
    SELECT 21001 AS appointment_id, 2001 AS patient_id, UNISTR('\BC15\C11C\C900') AS patient_name, 'INTERNAL' AS department_code, 'lee.doctor'  AS doctor_id, 'BOOKED' AS status, TRUNC(SYSDATE) + INTERVAL '10' HOUR AS scheduled_at FROM dual UNION ALL
    SELECT 21002,                   2002,                UNISTR('\C774\C9C0\C740'),                  'SURGERY',                    'kim.doctor',              'BOOKED',            TRUNC(SYSDATE) + INTERVAL '14' HOUR              FROM dual UNION ALL
    SELECT 21003,                   2003,                UNISTR('\AE40\BBFC\C218'),                  'INTERNAL',                   'park.doctor',             'BOOKED',            TRUNC(SYSDATE) + INTERVAL '16' HOUR              FROM dual
) s ON (t.appointment_id = s.appointment_id)
WHEN MATCHED THEN
    UPDATE SET t.patient_id = s.patient_id, t.patient_name = s.patient_name,
               t.department_code = s.department_code, t.doctor_id = s.doctor_id,
               t.status = s.status, t.scheduled_at = s.scheduled_at, t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (appointment_id, patient_id, patient_name, department_code, doctor_id, status, scheduled_at, created_at, updated_at)
    VALUES (s.appointment_id, s.patient_id, s.patient_name, s.department_code, s.doctor_id, s.status, s.scheduled_at, TRUNC(SYSDATE), SYSTIMESTAMP);

-- ── admin_reservation (접수화면 예약 CRUD용) ─────────────────
-- [핵심] Reservation Entity @Table=admin_reservation → 이 테이블 시드 없으면 예약 0건 + checkIn 404
MERGE INTO admin_reservation t
USING (
    SELECT 21001 AS reservation_id, 2001 AS patient_id, UNISTR('\BC15\C11C\C900') AS patient_name, 'INTERNAL' AS department_code, 'lee.doctor'  AS doctor_id, TRUNC(SYSDATE) + INTERVAL '10' HOUR AS scheduled_at, 'BOOKED' AS status FROM dual UNION ALL
    SELECT 21002,                   2002,                UNISTR('\C774\C9C0\C740'),                  'SURGERY',                    'kim.doctor',              TRUNC(SYSDATE) + INTERVAL '14' HOUR,                   'BOOKED'              FROM dual UNION ALL
    SELECT 21003,                   2003,                UNISTR('\AE40\BBFC\C218'),                  'INTERNAL',                   'park.doctor',             TRUNC(SYSDATE) + INTERVAL '16' HOUR,                   'BOOKED'              FROM dual
) s ON (t.reservation_id = s.reservation_id)
WHEN MATCHED THEN
    UPDATE SET t.patient_name = s.patient_name, t.status = s.status, t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (reservation_id, patient_id, patient_name, department_code, doctor_id, scheduled_at, status, created_at, updated_at)
    VALUES (s.reservation_id, s.patient_id, s.patient_name, s.department_code, s.doctor_id, s.scheduled_at, s.status, TRUNC(SYSDATE), SYSTIMESTAMP);

-- ── admin_config (운영자 수동 설정값) ────────────────────────
MERGE INTO admin_config t
USING (SELECT 'emergency_count' AS config_key, '3' AS config_value, UNISTR('\C751\AE09 \BC31\C0C1 \C6B4\C601\C790 \C218\B3D9 \C124\C815\AC12 (0~10)') AS description FROM dual) s
ON (t.config_key = s.config_key)
WHEN MATCHED THEN
    UPDATE SET t.config_value = s.config_value, t.updated_at = SYSTIMESTAMP
WHEN NOT MATCHED THEN
    INSERT (config_key, config_value, description, updated_at)
    VALUES (s.config_key, s.config_value, s.description, SYSTIMESTAMP);

COMMIT;
