-- =============================================================================
-- adminMasterService Seed Data (V2) — Oracle Edition
-- [MODIFIED] INSERT IGNORE → MERGE INTO
-- [MODIFIED] true/false → 1/0 (Oracle BOOLEAN 미지원)
-- [REMOVED] ALTER TABLE AUTO_INCREMENT → Oracle IDENTITY 자동 관리, 불필요
-- [ADDED] DELETE 후 MERGE: 6번 이상 staff_profile 정리 로직 유지
-- =============================================================================

-- ── department 초기 데이터 ──────────────────────────────────────────────
-- [ADDED] staff_profile(department_id=1,2,3) 참조 선행 삽입
--         department 테이블에 FK는 없지만 mapBackendToUi() 부서명 매핑에 필요
MERGE INTO department t
    USING (
        SELECT 1 AS department_id, 'INTERNAL'   AS code, '내과'       AS name, 1 AS active FROM dual UNION ALL
        SELECT 2,                   'SURGERY',            '외과',                1             FROM dual UNION ALL
        SELECT 3,                   'RADIOLOGY',          '영상의학과',           1             FROM dual
    ) s ON (t.code = s.code)
    WHEN MATCHED THEN
        UPDATE SET t.name = s.name, t.active = s.active
    WHEN NOT MATCHED THEN
        INSERT (code, name, active) VALUES (s.code, s.name, s.active);

-- ── staff_profile 초기 데이터 ────────────────────────────────────────────
-- [ADDED] 먼저 6번 이상 잘못 생성된 데이터 정리 (MySQL V2와 동일 의도)
DELETE FROM staff_profile WHERE staff_profile_id >= 6;

MERGE INTO staff_profile t
    USING (
        SELECT 1  AS staff_profile_id, 'lee.doctor'  AS login_id, '이순신'   AS name, 'DOCTOR' AS job_type, 1 AS department_id, '010-1111-1111' AS phone, 'lee@hospital.local'  AS email, 1 AS active FROM dual UNION ALL
        SELECT 2,                       'kim.doctor',              '김시민',             'DOCTOR',            2,                  '010-2222-2222',           'kim@hospital.local',             1             FROM dual UNION ALL
        SELECT 3,                       'park.doctor',             '박혁거세',           'DOCTOR',            3,                  '010-3333-3333',           'park@hospital.local',            1             FROM dual UNION ALL
        SELECT 4,                       'adm1',                    '원무1',              'ADMIN',             NULL,               '010-4444-4444',           'adm1@hospital.local',            1             FROM dual UNION ALL
        SELECT 5,                       'adm2',                    '원무2',              'ADMIN',             NULL,               '010-5555-5555',           'adm2@hospital.local',            1             FROM dual
    ) s ON (t.staff_profile_id = s.staff_profile_id)
    WHEN MATCHED THEN
        UPDATE SET
            t.login_id      = s.login_id,
            t.name          = s.name,
            t.job_type      = s.job_type,
            t.department_id = s.department_id,
            t.phone         = s.phone,
            t.email         = s.email,
            t.active        = s.active
    WHEN NOT MATCHED THEN
        -- [MODIFIED] OVERRIDING SYSTEM VALUE 제거
        -- 이유: V1에서 GENERATED BY DEFAULT ON NULL AS IDENTITY로 변경 → 명시값 삽입 허용
        --       Flyway Community 파서가 OVERRIDING SYSTEM VALUE를 독립 문장으로 오파싱 → ORA-00926
        INSERT (staff_profile_id, login_id, name, job_type, department_id, phone, email, active)
            VALUES (s.staff_profile_id, s.login_id, s.name, s.job_type, s.department_id, s.phone, s.email, s.active);