-- =============================================================================
-- adminMasterService Seed Data (V3) — Oracle Edition
-- [MODIFIED] INSERT IGNORE → MERGE INTO
-- [MODIFIED] NOW() → SYSTIMESTAMP
-- [REMOVED] ALTER TABLE AUTO_INCREMENT → Oracle IDENTITY 자동 관리
-- =============================================================================

MERGE INTO admin_visit t
    USING (
        SELECT 11001 AS visit_id, 2001 AS patient_id, '박서준' AS patient_name, 'INTERNAL' AS department_code, 'lee.doctor'  AS doctor_id, 'WAITING'      AS status FROM dual UNION ALL
        SELECT 11002,             2001,                '박민재',                  'INTERNAL',                   'lee.doctor',               'IN_TREATMENT'           FROM dual UNION ALL
        SELECT 11003,             2002,                '정수현',                  'INTERNAL',                   'kim.doctor',               'WAITING'                FROM dual UNION ALL
        SELECT 11004,             2003,                '이지은',                  'INTERNAL',                   'park.doctor',              'WAITING'                FROM dual UNION ALL
        SELECT 11005,             2002,                '박서준',                  'INTERNAL',                   'kim.doctor',               'WAITING'                FROM dual UNION ALL
        SELECT 11006,             2002,                '최수진',                  'INTERNAL',                   'park.doctor',              'WAITING'                FROM dual
    ) s ON (t.visit_id = s.visit_id)
    WHEN MATCHED THEN
        UPDATE SET
            t.patient_id      = s.patient_id,
            t.patient_name    = s.patient_name,
            t.department_code = s.department_code,
            t.doctor_id       = s.doctor_id,
            t.status          = s.status,
            t.updated_at      = SYSTIMESTAMP
    WHEN NOT MATCHED THEN
        -- [MODIFIED] OVERRIDING SYSTEM VALUE 제거 (V1 GENERATED BY DEFAULT ON NULL 변경으로 불필요)
        INSERT (visit_id, patient_id, patient_name, department_code, doctor_id, status, created_at, updated_at)
            VALUES (s.visit_id, s.patient_id, s.patient_name, s.department_code, s.doctor_id, s.status, SYSTIMESTAMP, SYSTIMESTAMP);