-- =============================================================================
-- adminMasterService V4 — patient_id IDENTITY 전환 (POST_PRESENTATION_TODO B-2)
-- =============================================================================
-- 배경: patient 테이블만 유일하게 PK가 수동 채번(NUMBER NOT NULL)이었음.
--       나머지 15개 테이블은 모두 GENERATED BY DEFAULT ON NULL AS IDENTITY.
--       → 프론트엔드가 Date.now()로 임시 ID를 발명해 INSERT하던 구조적 결함의 근본 원인.
-- 조치: patient_id를 다른 테이블과 동일한 IDENTITY 컬럼으로 통일.
--       START WITH 3000 — 시드 환자(2001~2005) 및 과거 임시 ID와 비충돌.
--       BY DEFAULT ON NULL 유지 → 시드 SQL의 명시적 ID INSERT는 계속 허용.
-- =============================================================================

ALTER TABLE patient MODIFY patient_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 3000);
