-- =============================================================================
-- Clinical Service — V1 통합 (Oracle Edition)
-- 구성: 스키마 DDL 전체 (V1 + V2 통합)
-- Target DB: his_clinical (Oracle XE 21c / XEPDB1)
-- =============================================================================

-- ============================================================
-- SECTION 1: DDL — 테이블 생성
-- ============================================================

CREATE TABLE order_header (
    order_id          NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    category          VARCHAR2(255)  NOT NULL,
    created_at        TIMESTAMP(6)   NOT NULL,
    deleted           NUMBER(1)      NOT NULL,
    deleted_at        TIMESTAMP(6)   NULL,
    deleted_by        VARCHAR2(100)  NULL,
    deleted_reason    VARCHAR2(255)  NULL,
    idempotency_key   VARCHAR2(255)  NULL,
    primary_item_code VARCHAR2(50)   NULL,
    primary_item_name VARCHAR2(100)  NULL,
    status            VARCHAR2(255)  NOT NULL,
    updated_at        TIMESTAMP(6)   NULL,
    visit_id          NUMBER         NOT NULL,
    CONSTRAINT pk_order_header PRIMARY KEY (order_id),
    CONSTRAINT uk_order_header_idem UNIQUE (idempotency_key)
);

CREATE TABLE order_item (
    order_item_id NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    item_code     VARCHAR2(255)  NOT NULL,
    item_name     VARCHAR2(255)  NOT NULL,
    order_id      NUMBER         NOT NULL,
    quantity      NUMBER(10)     NOT NULL,
    CONSTRAINT pk_order_item PRIMARY KEY (order_item_id)
);

CREATE TABLE visit_soap (
    visit_id        NUMBER         NOT NULL,
    archived        NUMBER(1)      NOT NULL,
    archived_at     TIMESTAMP(6)   NULL,
    archived_by     VARCHAR2(100)  NULL,
    archived_reason VARCHAR2(255)  NULL,
    assessment      VARCHAR2(4000) NULL,
    created_at      TIMESTAMP(6)   NOT NULL,
    objective       VARCHAR2(4000) NULL,
    plan            VARCHAR2(4000) NULL,
    subjective      VARCHAR2(4000) NULL,
    updated_at      TIMESTAMP(6)   NOT NULL,
    version_no      NUMBER(10)     NOT NULL,
    CONSTRAINT pk_visit_soap PRIMARY KEY (visit_id)
);

CREATE TABLE visit_soap_history (
    history_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    assessment  VARCHAR2(4000) NULL,
    captured_at TIMESTAMP(6)   NOT NULL,
    captured_by VARCHAR2(100)  NULL,
    objective   VARCHAR2(4000) NULL,
    plan        VARCHAR2(4000) NULL,
    subjective  VARCHAR2(4000) NULL,
    version_no  NUMBER(10)     NOT NULL,
    visit_id    NUMBER         NOT NULL,
    CONSTRAINT pk_visit_soap_history PRIMARY KEY (history_id)
);

CREATE TABLE encounter_note (
    note_id         NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    archived        NUMBER(1)      NOT NULL,
    archived_at     TIMESTAMP(6)   NULL,
    archived_by     VARCHAR2(100)  NULL,
    archived_reason VARCHAR2(255)  NULL,
    created_at      TIMESTAMP(6)   NOT NULL,
    note            VARCHAR2(4000) NOT NULL,
    updated_at      TIMESTAMP(6)   NULL,
    updated_by      VARCHAR2(100)  NULL,
    visit_id        NUMBER         NOT NULL,
    CONSTRAINT pk_encounter_note PRIMARY KEY (note_id)
);

CREATE TABLE final_order (
    final_order_id  NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    created_at      TIMESTAMP(6)   NOT NULL,
    idempotency_key VARCHAR2(80)   NOT NULL,
    note            VARCHAR2(400)  NULL,
    status          VARCHAR2(32)   NOT NULL,
    type            VARCHAR2(32)   NOT NULL,
    updated_at      TIMESTAMP(6)   NOT NULL,
    visit_id        NUMBER         NOT NULL,
    CONSTRAINT pk_final_order PRIMARY KEY (final_order_id),
    CONSTRAINT idx_final_order_idem UNIQUE (idempotency_key)
);
CREATE INDEX idx_final_order_visit  ON final_order (visit_id);
CREATE INDEX idx_final_order_status ON final_order (status);

CREATE TABLE outbox_event (
    id             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    event_id       VARCHAR2(64)   NOT NULL,
    aggregate_type VARCHAR2(32)   NOT NULL,
    aggregate_id   VARCHAR2(64)   NOT NULL,
    event_type     VARCHAR2(64)   NOT NULL,
    topic          VARCHAR2(128)  NOT NULL,
    partition_key  VARCHAR2(128)  NULL,
    payload        CLOB           NOT NULL,
    status         VARCHAR2(20)   NOT NULL,
    fail_count     NUMBER(10)     DEFAULT 0 NOT NULL,
    last_error     VARCHAR2(4000) NULL,
    created_at     TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    published_at   TIMESTAMP      NULL,
    CONSTRAINT pk_clinical_outbox_event PRIMARY KEY (id),
    CONSTRAINT uk_clinical_outbox_event_id UNIQUE (event_id)
);
CREATE INDEX idx_outbox_status_created      ON outbox_event (status, created_at);
CREATE INDEX idx_outbox_aggregate           ON outbox_event (aggregate_type, aggregate_id);
CREATE INDEX ix_outbox_topic_status_created ON outbox_event (topic, status, created_at);

CREATE TABLE consumer_processed_event (
    id           NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL,
    event_id     VARCHAR2(64)   NOT NULL,
    processed_at TIMESTAMP(6)   NOT NULL,
    CONSTRAINT pk_clinical_cpe PRIMARY KEY (id),
    CONSTRAINT uk_clinical_processed_event_id UNIQUE (event_id)
);

-- [통합 V2] visit_clinical_status: 진료 화면 진입 상태 추적
CREATE TABLE visit_clinical_status (
    visit_id        NUMBER        NOT NULL,
    clinical_status VARCHAR2(40)  DEFAULT 'SOAP_IN_PROGRESS' NOT NULL,
    updated_at      TIMESTAMP(6)  NOT NULL,
    CONSTRAINT pk_visit_clinical_status PRIMARY KEY (visit_id)
);
CREATE INDEX idx_vcs_status ON visit_clinical_status (clinical_status);

-- 상태 값 참고:
-- SOAP_IN_PROGRESS     : SOAP 작성 중
-- EXAM_REQUESTED       : 검사 요청 완료
-- EXAM_IN_PROGRESS     : Support worklist 생성 완료
-- FINAL_ORDER_READY    : DIAGNOSTIC_ORDER_COMPLETED 수신 → 최종오더 가능
-- FINAL_ORDER_CONFIRMED: 최종오더 확정
-- BILLABLE             : 후속 task 집계 완료
-- BILLED               : 청구 완료
