package kr.co.seoulit.his.admin.domain.master.patient;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "patient")
@Getter @Setter
@NoArgsConstructor @AllArgsConstructor @Builder
public class Patient {

    /**
     * 병원 전체에서 공통으로 사용되는 환자 식별자.
     * [B-2] 다른 15개 테이블과 동일하게 DB IDENTITY 채번으로 통일 (V4 마이그레이션).
     * 시드 SQL의 명시적 ID INSERT는 GENERATED BY DEFAULT 옵션으로 계속 허용된다.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long patientId;

    @Column(nullable = false)
    private String name;

    /** M/F/UNKNOWN */
    @Column(nullable = false)
    private String gender;

    /** 화면용 주민번호 마스킹 (예: 900101-1******) */
    private String rrnMasked;

    private LocalDate birthDate;
    private String phone;

    @Column(nullable = false)
    private Boolean active;

    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
